export const ALLSKILLS = {
  "HTML5": {icon: "https://img.icons8.com/color/48/000000/html-5.png" , name: "HTML5"},
  "CSS3": {icon: "https://img.icons8.com/color/48/000000/css3.png" , name: "CSS3"},
  "Sass": {icon: "https://img.icons8.com/color/48/000000/sass.png" , name: "Sass"},
  "Bootstrap": {icon: "https://img.icons8.com/color/48/000000/bootstrap.png" , name: "Bootstrap"},
  "jQuery": {icon: "https://img.icons8.com/ios-filled/48/000000/jquery.png" , name: "jQuery"},
  "Javascript": {icon: "https://img.icons8.com/color/48/000000/javascript.png" , name: "Javascript"},
  "TypeScript": {icon: "https://img.icons8.com/color/48/000000/typescript.png" , name: "TypeScript"},
  "React": {icon: "https://img.icons8.com/office/48/000000/react.png", name: "React" },
  "Redux": {icon: "https://img.icons8.com/color/48/000000/redux.png" , name: "Redux"},
  "Angular": {icon: "https://img.icons8.com/color/48/000000/angularjs.png" , name: "Angular"},
  "Git": {icon: "https://img.icons8.com/color/48/000000/git.png" , name: "Git"},
  "NodeJs": {icon: "https://img.icons8.com/color/48/000000/nodejs.png" , name: "NodeJs"},
  "GraphQL": {icon: "https://img.icons8.com/color/48/000000/graphql.png" , name: "GraphQL"},
  "Apollo": {icon: "https://img.icons8.com/color/48/000000/apollo.png" , name: "Apollo"},
  "Docker": {icon: "https://img.icons8.com/color/48/000000/docker.png" , name: "Docker"},
  "kubernetes": {icon: "https://img.icons8.com/color/48/000000/kubernetes.png" , name: "kubernetes"},
  "Webpack": {icon: "https://img.icons8.com/dusk/48/000000/webpack.png" , name: "Webpack"},
  "AWS": {icon: "https://img.icons8.com/color/48/000000/amazon-web-services.png" , name: "AWS"},
  "SQL": {icon: "https://img.icons8.com/ios-filled/48/000000/sql.png" , name: "SQL"},
  "MongDB": {icon: "https://img.icons8.com/color/48/000000/mongodb.png" , name: "MongDB"},
  "Firebase": {icon: "https://img.icons8.com/color/48/000000/firebase.png" , name: "Firebase"},
  "Redis": {icon: "https://img.icons8.com/color/48/000000/redis.png" , name: "Redis"},
  "Python": {icon: "https://img.icons8.com/color/48/000000/python.png" , name: "Python"},
  "Machine-Learning": { icon: "https://img.icons8.com/cute-clipart/64/000000/machine-learning.png", name: "Machine-Learning" },
  "Stripe": { icon: "https://img.icons8.com/color/48/000000/stripe.png", name: "Stripe" },
  "ExpressJs": { icon: "./images/expressjs.svg", name: "Express" },
};